services:
  db:
    image: redis/redis-stack:7.4.0-v8
    container_name: chat-app-db
    restart: always
    ports:
      - ${REDIS_PORT}:6379
      - ${REDIS_INSIGHT_PORT}:8001
    command: >
      redis-stack-server
      --save 20 1
      --appendonly yes
      --loglevel warning
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - dbvolume:/data

  backend:
    build: ../backend/
    container_name: chat-app-backend
    depends_on:
      - db
    environment:
      REDIS_HOST: db
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      FRONTEND_ADDRESS: http://localhost:${VITE_FRONTEND_PORT}
    ports:
      - ${VITE_BACKEND_PORT}:8080

volumes:
  dbvolume:
    
  