services:
  db:
    image: redis/redis-stack:7.4.0-v8
    container_name: chat-app-db
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: >
      redis-server
      --save 20 1
      --loglevel warning
      --requirepass ${REDIS_PASSWORD}
      --loadmodule /opt/redis-stack/lib/redisearch.so
      --loadmodule /opt/redis-stack/lib/rejson.so
    volumes:
      - dbvolume:/data

  backend:
    build: ../backend/
    container_name: chat-app-backend
    depends_on:
      - db
    environment:
      REDIS_HOST: db
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      FRONTEND_ADDRESS: http://localhost:${FRONTEND_PORT}
    ports:
      - ${BACKEND_PORT}:8080

volumes:
  dbvolume:
    
  